name: 🐞 Bug Report
description: Report a bug, issue, or broken behavior in a Lost Minions project.
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: What happened? What did you expect instead?
      placeholder: Describe the problem clearly and concisely.
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to…
        2. Click…
        3. See the error
  - type: input
    id: repo
    attributes:
      label: Repository
      placeholder: e.g. LostMinions.org-3DPrint
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Website
        - Automation / Script
        - 3D Print Design
        - Game Tool
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Add console output, screenshots, or error messages if helpful.
