name: ⚙️ Task / Maintenance
description: Routine work, cleanup, or automation improvements.
labels: [task]
body:
  - type: input
    id: repo
    attributes:
      label: Repository
      placeholder: e.g. LostMinions_Libraries
  - type: textarea
    id: description
    attributes:
      label: Task Description
      placeholder: What needs to be done or maintained?
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Normal
        - High
