name: 🧪 Compile

on:
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/compile.yml"
  workflow_call:
  workflow_dispatch:

jobs:
  compile:
    if: ${{ !endsWith(github.repository, '/.github') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 🧰 Minimal checkout for local actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
            .github/scripts
          fetch-depth: 1

      - name: 🧮 Check GitHub Actions usage
        uses: ./.github/actions/check-usage-action
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          org-name: ${{ github.repository_owner }}

      - name: 🧮 Check GitHub Packages usage
        uses: ./.github/actions/check-usage-package
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          org-name: ${{ github.repository_owner }}

      - name: ⚙️ Validate and Configure Git
        uses: ./.github/actions/setup-git
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: ⚙️ Setup .NET and NuGet
        uses: ./.github/actions/setup-dotnet-nuget
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          owner: ${{ github.repository_owner }}

      - name: 🧱 Build .NET Project
        id: build
        uses: ./.github/actions/build-dotnet

      - name: ✅ Verify Build Success
        shell: bash
        run: echo "✅ Build completed successfully."
