name: 🧪 Compile

on:
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/compile.yml"
  workflow_call:
  workflow_dispatch:

jobs:
  compile:
    if: ${{ !endsWith(github.repository, '/.github') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: ⚙️ Validate and Configure Git
        uses: ./.github/actions/setup-git
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: 🧮 Check GitHub Actions usage
        uses: ./.github/actions/check-usage
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          org-name: ${{ github.repository_owner }}

      - name: ⚙️ Setup .NET + NuGet
        uses: ./.github/actions/setup-dotnet-nuget
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          owner: ${{ github.repository_owner }}

      - name: 🏗️ Build .NET project
        uses: ./.github/actions/build-dotnet-solution

      - name: ✅ Verify Build Success
        shell: bash
        run: echo "✅ $(basename "$SOLUTION") built successfully."
