name: 📦 Publish Package

on:
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/publish.yml"
  workflow_call:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type (major, minor, patch)"
        required: false
        default: "patch"

permissions:
  contents: write
  packages: write

jobs:
  publish:
    if: ${{ !endsWith(github.repository, '/.github') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: ⚙️ Setup Git
        uses: ./.github/actions/setup-git
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: 🧮 Check GitHub Actions Usage
        uses: ./.github/actions/check-usage
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          org-name: ${{ github.repository_owner }}

      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: 📦 Publish .NET Package
        uses: ./.github/actions/build-dotnet-package
        with:
          bump: ${{ github.event.inputs.bump }}
          gh-token: ${{ secrets.GH_TOKEN }}
